name: swallpaper
description: Swallpaper - Cross-platform wallpaper manager for Windows and Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.0

  # Networking
  http: ^1.2.0

  # Storage
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0

  # UI
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # File
  path: ^1.9.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
